language: ruby
rvm:
  - 1.9.3
cache: bundler
before_install:
  - sudo apt-get update
  - sudo apt-get install aspell aspell-en
before_script:
  - git fetch origin
  - git submodule update --init
  - bundle exec jekyll build
script:
  - make lint links
  - bundle exec ruby ./tools/spellcheck/branch-spellcheck.rb $TRAVIS_BRANCH
  - ./compile.sh
branches:
  except:
    - master
notifications:
  email: false
