safe:        false
auto:        false
server:      false
#server_port: 4000
baseurl:    /
#url: http://localhost:4000

source:      ./
destination: ./_site
plugins:     ./_plugins
exclude: Procfile, Gemfile, Gemfile.lock, config.ru
future:      true
lsi:         false
pygments:    false
markdown:    kramdown
permalink:   /:categories/:title/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: ''
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
